version: "3.8"

services:
  backend:
    image: timakaa/lightweight-charts-extended-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
      - SOCKET_CORS_ORIGINS=http://localhost:3000
    restart: unless-stopped

  frontend:
    image: timakaa/lightweight-charts-extended-frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./client/.env
    restart: unless-stopped
