services:
  backend:
    container_name: "backend"
    image: timakaa/lightweight-charts-extended-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    container_name: "frontend"
    image: timakaa/lightweight-charts-extended-frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://100.76.193.76:8000}
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    env_file:
      - ./client/.env
    restart: unless-stopped
