"""add start_date and end_date to backtest_results

Revision ID: 0ef180b2980c
Revises: 
Create Date: 2025-07-12 21:17:30.442974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef180b2980c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_results', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('backtest_results', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_results', 'end_date')
    op.drop_column('backtest_results', 'start_date')
    # ### end Alembic commands ### 